name: Build & Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies
        run: yarn
        working-directory: music

      - name: Build production Artifact
        run: yarn build --if-present
        working-directory: music

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: |
            music/build

  deploy-frontend:
    name: Deploy Frontend to AWS S3
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download production artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: music/build

      - name: S3 Deployment Frontend
        run: aws s3 cp music/build s3://music.kevin-kraus.net/ --recursive

  deploy-backend:
    name: Deploy API to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Replace Spotify Client ID
        uses: jwsi/secret-parser@v1
        with:
          # File where GitHub Actions Secrets references should be parsed and replaced
          filename: music-api/function/spotifyService.js
          # Name of secret to search for in the designated file
          secret-name: "SPOTIFY_CLIENT_ID"
          # Value of secret to replace reference with in designated file
          secret-value: ${{ secrets.SPOTIFY_CLIENT_ID  }}

      - name: Replace Spotify Client Secret
        uses: jwsi/secret-parser@v1
        with:
          # File where GitHub Actions Secrets references should be parsed and replaced
          filename: music-api/function/spotifyService.js
          # Name of secret to search for in the designated file
          secret-name: "SPOTIFY_CLIENT_SECRET"
          # Value of secret to replace reference with in designated file
          secret-value: ${{ secrets.SPOTIFY_CLIENT_SECRET  }}

      - name: Install dependencies
        working-directory: music-api/function
        run: yarn
      
      - name: Build production Artifact
        working-directory: music-api/function
        run: yarn build

      - name: Create ZIP
        working-directory: music-api/function
        run: zip -j music-api.zip ./build/index.js
      
      - name: Upload ZIP to AWS Lambda
        working-directory: music-api/function
        env: 
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_REGION: "eu-central-1"
        run: aws lambda update-function-code --function-name get-spotify-playlists --zip-file fileb://music-api.zip

